//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FML.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PHASE1_GUI_DIALOG           102
#define IDD_FML_DIALOG                  102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDC_POINTER_COPY                105
#define IDC_NODROP                      106
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDB_BITMAP1                     132
#define IDD_CONFIG_DIR                  137
#define IDB_BITMAP2                     142
#define IDD_DIALOG1                     143
#define IDD_DATABASE_BROWSE             144
#define IDD_INT_RADIO                   145
#define IDD_IMPORT_SHOUTCAST            147
#define IDB_BITMAP3                     149
#define IDB_BITMAP4                     151
#define IDD_PROFILES                    152
#define IDD_PLAYLIST                    153
#define IDB_TREEBITMAP                  154
#define IDI_ICON1                       155
#define IDI_ICON2                       156
#define IDI_ICON3                       157
#define IDI_ICON4                       158
#define IDB_BITMAP6                     160
#define IDI_ICON5                       161
#define IDB_BITMAP5                     164
#define IDD_WAIT                        165
#define IDB_BITMAP7                     166
#define IDI_ICON6                       169
#define IDB_BITMAP8                     174
#define IDB_BITMAP9                     175
#define IDD_NEW_PLAYLIST                176
#define IDB_B4_OVER                     177
#define IDB_DROP1                       178
#define IDB_B1_DOWN                     179
#define IDB_B1_NORM                     180
#define IDB_B1_OVER                     181
#define IDB_DROP2                       183
#define IDB_B2_DOWN                     184
#define IDB_B2_NORM                     185
#define IDB_B2_OVER                     186
#define IDB_DROP3                       188
#define IDB_B3_DOWN                     189
#define IDB_B3_OVER                     191
#define IDB_B3_NORM                     192
#define IDB_B4_DOWN                     193
#define IDB_B4_NORM                     194
#define IDB_DROP4                       195
#define IDB_SPLASH                      196
#define IDB_B4_GREY                     198
#define IDB_B2_GREY                     199
#define IDB_B3_GREY                     200
#define IDB_B1_GREY                     201
#define IDB_BOTTOMBAR                   202
#define IDB_BLANK2                      232
#define IDB_FPBUTTON                    233
#define IDB_B1_FOCUS                    251
#define IDB_B2_FOCUS                    256
#define IDB_B3_FOCUS                    260
#define IDB_B4_FOCUS                    264
#define IDB_TOPBAR                      267
#define IDB_BLANK                       268
#define IDB_BOTTOMBAR550x50             273
#define IDB_BOTTOMBAR800x50             275
#define IDB_BOTTOMBAR700x50             276
#define IDB_B5_DOWN                     284
#define IDB_B5_OVER                     285
#define IDB_B5_NORM                     286
#define IDR_NO_HELP                     287
#define IDB_BOTTOM                      290
#define IDB_FML_TITLEBAR                327
#define IDB_A                           328
#define IDB_LEFTNAV_BG                  329
#define IDB_B                           330
#define IDB_TOPNAV                      331
#define IDB_C                           332
#define IDB_D                           333
#define IDB_E                           335
#define IDB_F                           336
#define IDB_IR_UP                       337
#define IDB_IR_OVER                     338
#define IDB_IR_DOWN                     340
#define IDB_IR_DISABLED                 342
#define IDB_CONFIG_UP                   343
#define IDB_CONFIG_OVER                 344
#define IDB_CONFIG_DOWN                 345
#define IDB_CONFIG_DISABLED             346
#define IDB_PLAYLIST_UP                 347
#define IDB_PLAYLIST_OVER               348
#define IDB_PLAYLIST_DOWN               349
#define IDB_PLAYLIST_DISABLED           350
#define IDB_FULLPLAY_UP                 351
#define IDB_FULLPLAY_OVER               352
#define IDB_MUSIC_AVAILABLE             353
#define IDB_PLAYLISTS                   354
#define IDB_TOPNAV2                     355
#define IDB_B_SAVE_UP                   356
#define IDB_B_SAVE_OVER                 357
#define IDB_B_SAVE_DOWN                 358
#define IDB_B_SAVE_DISABLED             359
#define IDB_B_LISTADD_UP                360
#define IDB_B_LISTADD_OVER              361
#define IDB_B_LISTADD_DOWN              362
#define IDB_B_LISTADD_DISABLED          363
#define IDB_B_LISTDELETE_UP             364
#define IDB_B_LISTDELETE_OVER           365
#define IDB_B_LISTDELETE_DOWN           366
#define IDB_B_LISTDELETE_DISABLED       367
#define IDB_B_LISTEDIT_UP               368
#define IDB_B_LISTEDIT_OVER             369
#define IDB_B_LISTEDIT_DOWN             370
#define IDB_B_LISTEDIT_DISABLED         371
#define IDB_LABEL_INFO                  376
#define IDB_LABEL_FINDER                377
#define IDB_INFO                        379
#define IDB_B_RADIOADD_UP               380
#define IDB_B_RADIOADD_OVER             381
#define IDB_B_RADIOADD_DOWN             382
#define IDB_B_RADIOADD_DISABLED         383
#define IDB_B_RADIODELETE_UP            384
#define IDB_B_RADIODELETE_OVER          385
#define IDB_B_RADIODELETE_DOWN          386
#define IDB_B_RADIODELETE_DISABLED      387
#define IDB_B_RADIOEDIT_UP              388
#define IDB_B_RADIOEDIT_OVER            389
#define IDB_B_RADIOEDIT_DOWN            390
#define IDB_B_RADIOEDIT_DISABLED        391
#define IDB_STATIONS_AVAILABLE          392
#define IDB_MYSTATIONS                  393
#define IDD_SCANDIALOG                  398
#define IDB_SEARCH_A                    399
#define IDB_SEARCH_B                    400
#define IDB_SEARCH_C                    401
#define IDB_BT_CANCEL_UP                403
#define IDB_BT_CANCEL_OVER              404
#define IDB_BT_CANCEL_DOWN              405
#define IDB_BT_CANCEL_DISABLED          406
#define IDD_DIALOG2                     408
#define IDB_NOTIFY_A                    409
#define IDB_NOTIFY_B                    410
#define IDB_NOTIFY_C                    411
#define ANIM_START_1                    416
#define ANIM_START_2                    417
#define ANIM_START_3                    418
#define ANIM_START_4                    419
#define ANIM_START_5                    420
#define ANIM_START_6                    421
#define ANIM_START_7                    422
#define ANIM_START_8                    423
#define ANIM_SEARCH_1                   424
#define ANIM_SEARCH_2                   425
#define ANIM_SEARCH_3                   426
#define ANIM_SEARCH_4                   427
#define ANIM_SEARCH_5                   428
#define ANIM_SEARCH_6                   429
#define ANIM_SEARCH_7                   430
#define ANIM_SEARCH_8                   431
#define ANIM_SEARCH_9                   432
#define ANIM_SEARCH_10                  433
#define ANIM_NOTIFY_1                   434
#define ANIM_NOTIFY_2                   435
#define ANIM_NOTIFY_3                   436
#define ANIM_NOTIFY_4                   437
#define ANIM_NOTIFY_5                   438
#define ANIM_NOTIFY_6                   439
#define IDI_ICON7                       444
#define IDB_B_SCAN_UP                   445
#define IDB_B_SCAN_OVER                 446
#define IDB_B_SCAN_DOWN                 447
#define IDB_B_SCAN_DISABLED             448
#define IDB_TREESTATES                  451
#define IDC_CONFIGURE                   1001
#define IDC_INTERNET                    1002
#define IDC_REFRESH                     1003
#define ID_HIDE                         1007
#define IDC_LIST1                       1010
#define IDC_ADD                         1011
#define IDC_REMOVE                      1012
#define IDC_TREE1                       1014
#define IDC_EDIT1                       1015
#define IDC_BUTTON_STOP                 1016
#define IDC_STATION_URL                 1016
#define IDC_EDIT_T_SORT                 1016
#define IDC_EDIT_T_FILTER               1017
#define IDC_ARTIST_NAME                 1018
#define IDC_EDIT_T_RETURN_CONTEXT       1018
#define IDC_ALBUM_NAME                  1019
#define IDC_SONG_TITLE                  1020
#define IDC_ARTIST_NUM                  1022
#define IDC_ALBUM_NUM                   1023
#define IDC_SONG_NUM                    1024
#define IDC_FRAME                       1025
#define IDC_GENRE                       1026
#define IDC_BUTTON_ADD_NEW              1026
#define IDC_PATH                        1027
#define IDC_IMPORT                      1028
#define IDC_SONG_GENRE                  1028
#define IDC_BUTTON_DELETE               1029
#define IDC_STATION_NAME                1030
#define IDC_STATION_LIST                1031
#define IDC_BUTTON_UPDATE               1032
#define IDC_STATUS                      1033
#define IDC_COMBO_SPEED                 1034
#define IDC_COMBO_GENRE                 1035
#define IDC_BUTTON_ADD                  1037
#define IDC_SHOUTCAST_LIST              1038
#define IDC_PROFILES                    1041
#define IDC_ADVANCED                    1042
#define IDC_DELETE                      1043
#define IDC_PLAYLISTS                   1043
#define IDC_EDIT_NAME                   1045
#define IDC_EDIT_PSWD                   1046
#define IDC_EDIT_PSWDCONFIRM            1047
#define IDC_UPDATE                      1048
#define IDC_ADDNEW                      1049
#define IDC_MEDIATREE                   1050
#define IDC_BUTTON_UP                   1051
#define IDC_BUTTON_DOWN                 1052
#define IDC_COMBO_PLAYLISTS             1053
#define IDC_PLAYLIST_LIST               1054
#define IDC_PLAYLIST_TITLE              1055
#define IDC_BUTTON_REMOVE               1055
#define IDC_BUTTONUpdate                1056
#define IDC_BUTTON6                     1057
#define IDC_BUTTON_NEW                  1057
#define IDC_PROGRESS1                   1057
#define IDC_HOTKEY1                     1058
#define IDC_TEST                        1060
#define IDC_EDIT_T_QUERYCONTEXT         1063
#define IDC_LIBRARY_NAME                1064
#define IDC_ST_PLAYLISTS                1066
#define IDC_ST_INTERNET_RADIO           1067
#define IDC_ST_CONFIGURE                1068
#define IDC_ST_HELP                     1069
#define IDC_PLAYLIST_TREE               1072
#define IDC_NEWPLAYLIST                 1075
#define IDC_SAVECHANGES                 1076
#define IDC_TREE_LISTCTRL               1079
#define IDC_BUTTON1                     1080
#define IDC_ST_FULLPLAY                 1081
#define IDC_TOPBAR                      1085
#define IDC_BLANK                       1086
#define IDC_CONNECT                     1087
#define IDC_BLANK3                      1088
#define IDC_DISPLAY_TEXT                1088
#define IDC_ARTIST                      1090
#define IDC_ALBUM                       1091
#define IDC_TITLE                       1092
#define IDC_NUMARTISTS                  1093
#define IDC_NUMALBUMS                   1094
#define IDC_NUMTITLES                   1095
#define IDC_NUMGENRES                   1096
#define IDC_STATIC_MEDIA_FRAME          1097
#define IDC_STATIC_PLAYLIST_FRAME       1098
#define IDC_OK                          1102
#define ID_IMLMENU_OPEN                 32779
#define IDC_MENU_EXIT                   32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        453
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
